apps/team/urls.py
from django.urls import path
from .views import team, add_team, edit_team, activate_team, invite

app_name = "team"

urlpatterns = [
    path("add_team/", add_team, name="add_team"),
    path("edit_team/", edit_team, name="edit_team"),
    path("invite/", invite, name="invite"),
    path("activate_team/<int:team_id>", activate_team, name="activate_team"),
    path("<int:team_id>/", team, name="team"),
]

apps/userprofile/urls.py
from django.urls import path
from apps.userprofile.views import myaccount, edit_profile, accept_invitation
from . import views

urlpatterns = [
    path("myaccount/", myaccount, name="myaccount"),
    path("edit_profile/", edit_profile, name="edit_profile"),
    path("accept_invitation/", accept_invitation, name="accept_invitation"),
    path("password_change", views.password_change, name="password_change"),
]

workingtime/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.main.views import home, privacy, terms, plans, signup, login_view
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", home, name="home"),
    path("privacy", privacy, name="privacy"),
    path("terms", terms, name="terms"),
    path("plans", plans, name="plans"),
    path('admin/', admin.site.urls),

    path("signup/", signup, name="signup"),
    path("login/", login_view, name="login"),
    # path("login/", auth_views.LoginView.as_view(template_name="main/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("dashboard/", include("apps.dashboard.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/team/models.py
from django.db import models
from django.contrib.auth.models import User


class Team(models.Model):
    ACTIVE = "active"
    DELETED = "deleted"

    CHOICES_STATUS = (
        (ACTIVE, "Active"),
        (DELETED, "Deleted"),
    )

    title = models.CharField(max_length=255)
    members = models.ManyToManyField(User, related_name="teams")
    created_by = models.ForeignKey(User, related_name="created_teams", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=ACTIVE)

    class Meta:
        ordering = ["title"]

    def __str__(self):
        return self.title


class Invitation(models.Model):

    # Status
    INVITED = "invited"
    ACCEPTED = "accepted"

    CHOICES_STATUS = (
        (INVITED, "Invited"),
        (ACCEPTED, "Accepted"),
    )

    team = models.ForeignKey(Team, related_name="invitations", on_delete=models.CASCADE)
    email = models.EmailField()
    code = models.CharField(max_length=20)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=INVITED)
    date_sent = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

apps/userprofile/models.py
import uuid
from django.contrib.auth.models import User
from django.db import models


class Userprofile(models.Model):

    user = models.OneToOneField(User, related_name="userprofile", on_delete=models.CASCADE)
    active_team_id = models.IntegerField(default=0)
    avatar = models.ImageField(upload_to='uploads/avatars/', blank=True, null=True)

    def get_avatar(self):
        if self.avatar:
            return self.avatar.url
        else:
            return "/static/images/avatar.png"

    def __str__(self):
        return self.user.username

apps/userprofile/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import SetPasswordForm


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)


class Meta(NewUserForm):
    model = User
    fields = ("email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class ChangePasswordForm(SetPasswordForm):
    class Meta:
        model = get_user_model()
        fields = ['new_password1', 'new_password2']

apps/userprofile/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib import messages
from apps.team.models import Team, Invitation
from .forms import NewUserForm
from apps.team.utilities import send_invitation_accepted
from .forms import ChangePasswordForm


@login_required(login_url='login')
def myaccount(request):
    teams = request.user.teams.exclude(pk=request.user.userprofile.active_team_id)
    invitations = Invitation.objects.filter(email=request.user.email, status=Invitation.INVITED)

    return render(request, "userprofile/myaccount.html", {"teams": teams, "invitations": invitations})


@login_required(login_url='login')
def edit_profile(request):
    if request.method == "POST":
        request.user.first_name = request.POST.get("first_name", "")
        request.user.last_name = request.POST.get("last_name", "")
        request.user.email = request.POST.get("email", "")
        request.user.save()

        if request.FILES:
            avatar = request.FILES['avatar']
            userprofile = request.user.userprofile
            userprofile.avatar = avatar
            userprofile.save()

        messages.info(request, "Your changes were saved successfully")

        return redirect("myaccount")

    return render(request, "userprofile/edit_profile.html")


@login_required(login_url='login')
def password_change(request):
    user = request.user
    if request.method == 'POST':
        form = ChangePasswordForm(user, request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Your password has been changed")
            return redirect('login')
        else:
            for error in list(form.errors.values()):
                messages.error(request, error)

    form = ChangePasswordForm(user)
    return render(request, 'userprofile/password_reset_confirm.html', {'form': form})


@login_required(login_url='login')
def accept_invitation(request):
    if request.method == 'POST':
        code = request.POST.get('code')

        invitations = Invitation.objects.filter(code=code, email=request.user.email)

        if invitations:
            invitation = invitations[0]
            invitation.status = Invitation.ACCEPTED
            invitation.save()

            team = invitation.team
            team.members.add(request.user)
            team.save()

            userprofile = request.user.userprofile
            userprofile.active_team_id = team.id
            userprofile.save()

            messages.info(request, 'Invitation has been accepted')

            send_invitation_accepted(team, invitation)

            return redirect('team:team', team_id=team.id)
        else:
            messages.info(request, 'Invitation was not found')
    else:
        return render(request, 'userprofile/accept_invitation.html')

apps/userprofile/templates/userprofile/accept_invitation.html
{% extends 'main/base.html' %}

{% block title %}Accept invitation | {% endblock %}

{% block content %}
    <br>
    <nav class="breadcrumb" aria-label="breadcrumb">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url "myaccount" %}">My account</a></li>
            <li class="is-active"><a href="{% url "accept_invitation" %}" aria-current="page">Accept invitation</a></li>
        </ul>
    </nav>

    <div class="columns is">
        <div class="column is-4 is-offset-4">
            <h1 class="title">Accept invitation</h1>

            <form method="post" action=".">
                {% csrf_token %}
                <div class="field">
                    <label>Enter your code here</label>
                    <div class="control">
                        <input type="text" name="code" id="id_code" class="input">
                    </div>
                </div>

                <div class="field">
                    <div class="control">
                        <button class="button is-success">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

apps/userprofile/templates/userprofile/edit_profile.html
{% extends 'main/base.html' %}

{% block title %}Edit profile | {% endblock %}

{% block content %}
    <br>
    <nav class="breadcrumb" aria-label="breadcrumb">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url "myaccount" %}">My account</a></li>
            <li class="is-active"><a href="{% url "edit_profile" %}" aria-current="page">Edit profile</a></li>
        </ul>
    </nav>

    <div class="columns is">
        <div class="column is-4 is-offset-4">
            <h1 class="title">Edit profile</h1>

            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}

                <div class="field">
                    <label>First name</label>
                    <div class="control">
                        <input type="text" name="first_name" id="first_name" class="input" \
                                {% if request.user.first_name %} value="{{ request.user.first_name }}"{% endif %}>
                    </div>
                </div>

                <div class="field">
                    <label>Last name</label>
                    <div class="control">
                        <input type="text" name="last_name" id="last_name" class="input" \
                                {% if request.user.last_name %} value="{{ request.user.last_name }}"{% endif %}>
                    </div>
                </div>

                <div class="field">
                    <label>E-mail</label>
                    <div class="control">
                        <input type="text" name="email" id="email" class="input" \
                                {% if request.user.email %} value="{{ request.user.email }}"{% endif %}>
                    </div>
                </div>

                <div class="field">
                    <label>Avatar</label>
                    <figure class="image is-64x64">
                        <img src="{{ request.user.userprofile.get_avatar }}">
                    </figure>
                    <div class="control mt-2">
                        <input type="file" name="avatar" id="id_avatar" class="input">
                    </div>
                </div>

                <div class="field">
                    <div class="control">
                        <button class="button is-success">Save changes</button>
                        <form>
                            <input class="button" value="Back" onclick="history.back()">
                        </form>
                    </div>
                </div>
            </form>

        </div>
    </div>
{% endblock %}

apps/userprofile/templates/userprofile/myaccount.html
{% extends 'main/base.html' %}

{% block title %}My account |{% endblock %}

{% block content %}
    <br>
    <nav class="breadcrumb" aria-label="breadcrumb">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li class="is-active"><a href="{% url "myaccount" %}" aria-current="page">My account</a></li>
        </ul>
    </nav>
    <div class="columns">
        <div class="column is-6 is-offset-5">
            <div class="media mb-4">
                <div class="media-left">
                    <figure class="image is-64x64">
                        <img src="{{ user.userprofile.get_avatar }}">
                    </figure>
                </div>
                <div class="media-content">
                    <p class="title is-3">{% firstof user.get_full_name user.username %}</p>
                    <p class="subtitle is-6">{{ user.email }}</p>
                </div>
            </div>
            <a href="{% url "edit_profile" %}" class="button is-info">
                <span class="icon"><i class="far fa-edit"></i></span>
                <span>Edit profile</span>
            </a>
            <a href="{% url 'password_change' %}" class="button is-danger">
                <span class="icon"><i class="far fa-eye"></i></span>
                <span>Change password</span>
            </a>
        <hr>
            <div>
                {% if request.user.is_staff %}
                    <a href="{% url 'signup' %}" class="button is-warning">
                        <span class="icon"><i class="far fa-user"></i></span>
                        <span>Create user</span>
                    </a>
                {% endif %}
                <a href="{% url "logout" %}" class="button is-danger">
                    <span class="icon"><i class="fas fa-sign-out-alt"></i></span>
                    <span>Log out</span>
                </a>
            </div>
        </div>
    </div>

    <hr>

    {% if invitations %}
        <div class="notification is-info">
            <h2 class="subtitle">You have pending invitations</h2>
            {% for invitation in invitations %}
                <a href="{% url 'accept_invitation' %}">{{ invitation.team.title }}</a>
            {% endfor %}
        </div>
    {% endif %}

    <div class="columns">
    <div class="column is-12">
        <h2 class="subtitle">Teams</h2>
        {% if request.user.is_staff %}
            <a href="{% url 'team:add_team' %}" class="button is-success">Add Team</a>
        {% endif %}
    </div>
    </div>

    <div class="columns">
    {% if active_team %}
        <div class="column is-4">
                <div class="notification has-background-success-light">
                    <h3 class="is-size-5">{{ active_team.title }}{% if active_team.created_by == request.user %}(Owner)
                                                          {% else %}(Member){% endif %}
                    </h3>

                <hr>

                <a href="{% url "team:team" active_team.id %}" class="button is-success">Details</a>

                {% if active_team.created_by == request.user %}
                    <a href="{% url 'team:invite' %}" class="button is-info">Invite users</a>
                {% endif %}
                </div>
            </div>
    {% endif %}
        {% for team in teams %}
            <div class="column is-4">
                <div class="notification">
                    <h3 class="is-size-5">{{ team.title }}{% if team.created_by == request.user %}(Owner)
                                                          {% else %}(Member){% endif %}
                    </h3>

                <hr>

                <a href="{% url 'team:team' team.id %}" class="button is-success">Details</a>
                <a href="{% url "team:activate_team" team.id %}" class="button is-info">Activate</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

apps/userprofile/templates/userprofile/password_reset_confirm.html
{% extends "main/base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <div class="column is-4 is-offset-4">
            <h1 class="title">Change password</h1>
            <h2>Password Reset Confirm</h2><hr>
            <p>Please enter your new password.</p>
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="button is-danger" type="submit">Reset password</button>
                <form>
                    <input class="button" value="Back" onclick="history.back()">
                </form>
            </form>
        </div>
    </div>
{% endblock %}

apps/userprofile/templates/userprofile/signup_new.html
{% extends 'main/base.html' %}
{% load crispy_forms_filters %}


{% block content %}
    {% load crispy_forms_tags %}
    <section class="hero is-small is-light is-bold">
        <div class="hero-body" style="background-color: #e3b39f">
            <div class="container" style="background-color: #e3b39f">
                <h1 class="title">Sign up</h1>
                <h2 class="subtitle">Create your personal account and start tracking your work time.</h2>
            </div>
        </div>
    </section>
    <div class="container py-5">
        <h1>Register</h1>
        <form method="POST">
            {% csrf_token %}
            {{ register_form|crispy }}
            <button class="btn btn-primary" type="submit">Register</button>
        </form>
        <p class="text-center">If you already have an account, <a href="{% url "login" %}">login</a> instead.</p>
    </div>

{% endblock %}

apps/userprofile/templates/userprofile/signup_old.html
{% extends 'main/base.html' %}

{% block title %}Sign Up |{% endblock %}

{% block content %}

    <div class="columns" id="signup-app">
        <div class="column is-6 is-offset-3">
            <form method="post" action="." class="mt-6" v-on="validateForm" novalidate>
                {% csrf_token %}

                {% if form.errors %}
                    <div class="notification is-danger">
                        {{ form.non_field_errors }}

                        {% for field in form %}
                            {% if field.errors %}{{ field.label }}:
                                {{ field.errors|striptags}}
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endif %}
                <div class="notification is-danger" v-if="errors.length">
                    <p v-for="error in errors">
                        [[ error ]]
                    </p>
                </div>
                <div class="field">
                    <label>E-mail</label>
                    <div class="control">
                        <input type="email" name="username" id="id_username" class="input" v-model="username">
                    </div>
                </div>

                <div class="field">
                    <label>Password</label>
                    <div class="control">
                        <input type="password" name="password1" id="id_password1" class="input" v-model="password1">
                    </div>
                </div>

                <div class="field">
                    <label>Repeat password</label>
                    <div class="control">
                        <input type="password" name="password2" id="id_password2" class="input" v-model="password2">
                    </div>
                </div>

                <ul class="password-helt-text">
                    <li v-if="password1.length < 8">Password must contain at least 8 characters!</li>
                    <li v-if="!isNaN(password1)">Password can't contain numbers only!</li>
                </ul>

                <div class="field">
                    <div class="control">
                        <button class="button is-success">Sign up</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        const SignupApp = {
            data() {
                return {
                    username: "",
                    password1: "",
                    password2: "",
                    errors: []
                }

            },
            delimiters: ['[[', ']]'],
            methods: {
                Validate: {
                    validateForm(e) {
                        this.errors = []
                        if (!this.validateEmail(this.username)) {
                            this.errors.push("The e-mail address is not valid")
                        }

                        if (this.password1 === "") {
                            this.errors.push("Password field cannot be empty")
                        }

                        if (this.password1.length < 8) {
                            this.errors.push("Password must be at least 8 characters")
                        }

                        if (!isNaN(this.password1)) {
                            this.errors.push("Password must contain letters and numbers")
                        }

                        if (this.password1 !== this.password2) {
                            this.errors.push("Passwords does not match!")
                        }
                        if (this.errors.length) {
                            e.preventDefault()
                            return false
                        }else {
                            return true
                        }
                    },
                },
                    validateEmail(email) {
                        if (/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/.test(email)) {
                            return true
                        }
                        return false
                    }
            }
        }

        Vue.createApp(SignupApp).mount("#signup-app")
    </script>
{% endblock %}