apps/project/urls.py
from django.urls import path
from .api import api_start_timer, api_stop_timer, api_discard_timer, api_get_tasks
from .views import projects, project, edit_project, task, edit_task, edit_entry, delete_entry, delete_untracked_entry, \
    track_entry, clone_project

app_name = "project"

urlpatterns = [
    path("", projects, name="projects"),
    path("<int:project_id>/", project, name="project"),
    path("<int:project_id>/<int:task_id>/", task, name="task"),
    path("<int:project_id>/<int:task_id>/edit/", edit_task, name="edit_task"),
    path("<int:project_id>/<int:task_id>/edit/<int:entry_id>/edit/", edit_entry, name="edit_entry"),
    path("<int:project_id>/<int:task_id>/edit/<int:entry_id>/delete/", delete_entry, name="delete_entry"),
    path("<int:project_id>/edit/", edit_project, name="edit_project"),
    path('delete_untracked_entry/<int:entry_id>/', delete_untracked_entry, name="delete_untracked_entry"),
    path('track_entry/<int:entry_id>/', track_entry, name='track_entry'),
    path('<int:project_id>/clone/', clone_project, name='clone_project'),


    path('api/start_timer/', api_start_timer, name="api_start_timer"),
    path('api/stop_timer/', api_stop_timer, name="api_stop_timer"),
    path('api/discard_timer/', api_discard_timer, name="api_discard_timer"),
    path('api/get_tasks/', api_get_tasks, name="api_get_tasks"),
]

workingtime/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.main.views import home, privacy, terms, plans, signup, login_view
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", home, name="home"),
    path("privacy", privacy, name="privacy"),
    path("terms", terms, name="terms"),
    path("plans", plans, name="plans"),
    path('admin/', admin.site.urls),

    path("signup/", signup, name="signup"),
    path("login/", login_view, name="login"),
    # path("login/", auth_views.LoginView.as_view(template_name="main/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("dashboard/", include("apps.dashboard.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/project/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import related

from apps.team.models import Team


class Project(models.Model):
    ACTIVE = 'active'
    ARCHIVED = 'archived'

    STATUS_CHOICES = (
        (ACTIVE, 'Active'),
        (ARCHIVED, 'Archived'),
    )

    team = models.ForeignKey(Team, related_name='projects', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=ACTIVE)
    created_by = models.ForeignKey(User, related_name='projects', on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["title"]

    def __str__(self):
        return self.title

    def registered_time(self):
        return sum(entry.minutes for entry in self.entries.all())

    def num_tasks_todo(self):
        return self.tasks.filter(status=Task.TODO).count()


class Task(models.Model):
    TODO = 'todo'
    DONE = 'done'
    ARCHIVED = 'archived'

    CHOICES_STATUS = (
        (TODO, 'Todo'),
        (DONE, 'Done'),
        (ARCHIVED, 'Archived'),
    )

    team = models.ForeignKey(Team, related_name='tasks', on_delete=models.CASCADE)
    project = models.ForeignKey(Project, related_name='tasks', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, related_name='tasks', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=TODO)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.title

    def registered_time(self):
        return sum(entry.minutes for entry in self.entries.all())


class Entry(models.Model):
    team = models.ForeignKey(Team, related_name='entries', on_delete=models.CASCADE)
    project = models.ForeignKey(Project, related_name='entries', on_delete=models.CASCADE, blank=True, null=True)
    task = models.ForeignKey(Task, related_name='entries', on_delete=models.CASCADE, blank=True, null=True)
    minutes = models.IntegerField(default=0)
    is_tracked = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='entries', on_delete=models.CASCADE)
    created_at = models.DateTimeField()

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        if self.task:
            return "%s - %s" % (self.task.title, self.created_at)

        return "%s" % self.created_at

apps/project/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from datetime import datetime
from copy import deepcopy

from .models import Project, Task, Entry
from apps.team.models import Team
from apps.main.decorators import allowed_users, admin_only


@login_required(login_url='login')
def projects(request):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    projects = team.projects.filter(status=Project.ACTIVE)
    archived_projects = team.projects.filter(status=Project.ARCHIVED)

    if request.method == "POST":
        title = request.POST.get('title')

        if title:
            project = Project.objects.create(team=team, title=title, created_by=request.user)

            messages.info(request, "Project was created successfully")

            return redirect('project:projects')

    return render(request, 'project/projects.html', {"team": team, "projects": projects, 'archived_projects': archived_projects})


@login_required(login_url='login')
def project(request, project_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    project = get_object_or_404(Project, team=team, pk=project_id)

    if request.method == 'POST':
        title = request.POST.get('title')

        if title:
            task = Task.objects.create(team=team, project=project, created_by=request.user, title=title)

            messages.info(request, 'Task was created successfully')

            return redirect("project:project", project_id=project.id)

    tasks_todo = project.tasks.filter(status=Task.TODO)
    tasks_done = project.tasks.filter(status=Task.DONE)
    tasks_archived = project.tasks.filter(status=Task.ARCHIVED)

    return render(request, "project/project.html",
                  {"team": team, "project": project, "tasks_todo": tasks_todo, "tasks_done": tasks_done,
                   'tasks_archived': tasks_archived})


@login_required(login_url='login')
@admin_only
def edit_project(request, project_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    project = get_object_or_404(Project, team=team, pk=project_id)

    if request.method == "POST":
        title = request.POST.get('title')
        status = request.POST.get('status')

        if title:
            project.title = title
            project.status = status
            project.save()

            messages.info(request, "Changes was saved successfully")

            return redirect("project:project", project_id=project.id)

    return render(request, "project/edit_project.html", {"team": team, "project": project})


@login_required(login_url='login')
def task(request, project_id, task_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    project = get_object_or_404(Project, team=team, pk=project_id)
    task = get_object_or_404(Task, pk=task_id, team=team)

    if request.method == "POST":
        hours = int(request.POST.get('hours', 0))
        minutes = int(request.POST.get('minutes', 0))
        date = '%s %s' % (request.POST.get('date'), datetime.now().time())
        total_minutes = (hours * 60) + minutes

        entry = Entry.objects.create(team=team, project=project, task=task, minutes=total_minutes,
                                     created_by=request.user, created_at=date, is_tracked=True)

    return render(request, "project/task.html",
                  {"today": datetime.today(), "team": team, "project": project, "task": task})


@login_required(login_url='login')
@admin_only
def edit_task(request, project_id, task_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    project = get_object_or_404(Project, team=team, pk=project_id)
    task = get_object_or_404(Task, pk=task_id, team=team)

    if request.method == "POST":
        title = request.POST.get('title')
        status = request.POST.get('status')

        if title:
            task.title = title
            task.status = status
            task.save()

            messages.info(request, "Task was saved successfully")

            return redirect('project:task', project_id=project_id, task_id=task_id)

    return render(request, "project/edit_task.html", {"team": team, "project": project, "task": task})


@login_required(login_url='login')
def edit_entry(request, project_id, task_id, entry_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    project = get_object_or_404(Project, team=team, pk=project_id)
    task = get_object_or_404(Task, pk=task_id, team=team)
    entry = get_object_or_404(Entry, pk=entry_id, team=team)

    if request.method == "POST":
        hours = int(request.POST.get('hours', 0))
        minutes = int(request.POST.get('minutes', 0))
        date = '%s %s' % (request.POST.get('date'), datetime.now().time())

        entry.created_at = date
        entry.minutes = (hours * 60) + minutes
        entry.save()
        messages.info(request, "Changes was saved successfully")

        return redirect('project:task', project_id=project_id, task_id=task_id)

    hours, minutes = divmod(entry.minutes, 60)

    context = {
        "team": team,
        "project": project,
        "task": task,
        "entry": entry,
        "hours": hours,
        "minutes": minutes,
    }

    return render(request, 'project/edit_entry.html', context)


@login_required(login_url='login')
def delete_entry(request, project_id, task_id, entry_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    project = get_object_or_404(Project, team=team, pk=project_id)
    task = get_object_or_404(Task, pk=task_id, team=team)
    entry = get_object_or_404(Entry, pk=entry_id, team=team)
    entry.delete()

    messages.info(request, "The entry has been deleted successfully")

    return redirect("project:task", project_id=project_id, task_id=task_id)


@login_required(login_url='login')
def delete_untracked_entry(request, entry_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    entry = get_object_or_404(Entry, pk=entry_id, team=team)
    entry.delete()

    messages.info(request, "The entry has been deleted successfully")

    return redirect("dashboard")


@login_required(login_url='login')
def track_entry(request, entry_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    entry = get_object_or_404(Entry, pk=entry_id, team=team)
    projects = team.projects.filter(status=Project.ACTIVE)

    if request.method == 'POST':
        hours = int(request.POST.get('hours', 0))
        minutes = int(request.POST.get('minutes', 0))
        project = request.POST.get('project')
        task = request.POST.get('task')

        if project and task:
            entry.project_id = project
            entry.task_id = task
            entry.minutes = (hours * 60) + minutes
            entry.created_at = '%s %s' % (request.POST.get('date'), entry.created_at.time())
            entry.is_tracked = True
            entry.save()

            messages.info(request, 'Your time has been tracked')

            return redirect('dashboard')

    hours, minutes = divmod(entry.minutes, 60)

    context = {
        'hours': hours,
        'minutes': minutes,
        'team': team,
        'projects': projects,
        'entry': entry,
    }

    return render(request, 'project/track_entry.html', context)


@login_required(login_url='login')
@admin_only
def clone_project(request, project_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    project = Project.objects.filter(team=team, pk=project_id).get()
    tasks = Task.objects.filter(project=project)
    new_project = deepcopy(project)

    if request.method == "POST":
        new_project.title = request.POST.get('title')
        new_project.team = project.team
        new_project.created_by = request.user
        new_project.create_at = datetime.now()
        new_project.pk = None

        new_project.save()

        for task in tasks:
            new_task = deepcopy(task)
            new_task.pk = None
            new_task.project = new_project
            new_task.save()

        messages.info(request, "Project was cloned successfully")

        return redirect("project:project", project_id=new_project.id)

    return render(request, "project/edit_project.html", {"team": team, "project": project})

apps/project/templates/project/edit_project.html
{% extends 'main/base.html' %}

{% block title %}Edit Project | {% endblock %}

{% block content %}
    <div id="project-app">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a href="#">Dashboard</a></li>
                <li><a href="{% url 'project:projects' %}">Projects</a></li>
                <li><a href="{% url 'project:project' project.id %}" aria-current="page">{{ project.title }}</a></li>
                <li class="is-active"><a href="{% url 'project:edit_project' project.id %}" aria-current="page">Edit
                    project</a></li>
            </ul>
        </nav>

        <div class="columns">
            <div class="column">
                <h1 class="title">Edit Project</h1>

                <div class="columns">
                    <div class="column is-4">
                        <form method="post" action=".">
                            {% csrf_token %}

                            <div class="field">
                                <label>Title</label>

                                <div class="control">
                                    <input type="text" name="title" id="id_title" class="input"
                                           value="{{ project.title }}">
                                </div>
                                <div class="field">
                                    <label>Status</label>
                                    <div class="control">
                                        <div class="select">
                                            <select name="status" id="id_status">
                                                <option value="active"{% if task.status == 'active' %}
                                                        selected{% endif %}>Active
                                                </option>
                                                <option value="archived"{% if task.status == 'archived' %}
                                                        selected{% endif %}>Archived
                                                </option>
                                            </select>
                                        </div>
                                    </div>
                                </div>

                                <div class="field">
                                    <div class="control">
                                        <button class="button is-success">Save changes</button>
                                        <a href="{{ request.META.HTTP_REFERER }}"><input class="button" name="Cancel" value="Cancel"></a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/project/templates/project/edit_task.html
{% extends 'main/base.html' %}

{% block title %}Edit task | {% endblock %}

{% block content %}
    <div id="project-app">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a href="#">Dashboard</a></li>
                <li><a href="{% url 'project:projects' %}">Projects</a></li>
                <li><a href="{% url 'project:project' project.id %}">{{ project.title }}</a></li>
                <li class="is-active"><a href="{% url 'project:edit_task' project.id task.id %}" aria-current="page">Edit task</a></li>
            </ul>
        </nav>

        <div class="columns">
            <div class="column">
                <h1 class="title">Edit task</h1>
            </div>
        </div>

        <div class="columns">
            <div class="column is-4">
                <form method="post" action=".">
                    {% csrf_token %}

                    <div class="field">
                        <label>Title</label>

                        <div class="control">
                            <input type="text" name="title" id="id_title" class="input" value="{{ task.title }}">
                        </div>
                    </div>

                    <div class="field">
                        <label>Status</label>
                        <div class="control">
                            <div class="select">
                                <select name="status" id="id_status">
                                    <option value="todo"{% if task.status == 'todo' %} selected{% endif %}>Todo</option>
                                    <option value="done"{% if task.status == 'done' %} selected{% endif %}>Done</option>
                                    <option value="archived"{% if task.status == 'archived' %} selected{% endif %}>Archived</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            <button class="button is-success">Save changes</button>
                            <button class="button" href="{% url 'project:projects'%}">Cancel</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

apps/project/templates/project/project.html
{% extends 'main/base.html' %}

{% block title %}{{ project.title }} | {% endblock %}

{% block content %}
    <div id="project-app">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a href="#">Dashboard</a></li>
                <li><a href="{% url 'project:projects' %}">Projects</a></li>
                <li class="is-active"><a href="{% url 'project:project' project.id %}"
                                         aria-current="page">{{ project.title }}</a></li>
            </ul>
        </nav>

        <div class="columns">
            <div class="column">
                <h1 class="title">{{ project.title }}</h1>

                <div class="buttons">
                    {% if request.user.is_staff %}
                        <a @click="showAddTaskModal = !showAddTaskModal" class="button is-success">Add task</a>
                        <a href="{% url 'project:edit_project' project.id %}" class="button is-warning">Edit project</a>
                        <a href="{% url 'project:clone_project' project.id %}" class="button is-danger">Clone project</a>
                    {% endif %}
                    <a class="button" href="{% url 'project:projects' %}">Back</a>
                </div>
            </div>
        </div>

        {% if not tasks_todo and not tasks_done %}
            <div class="columns">
                <div class="column is-3">
                    <div class="notification">
                        <p>There is no tasks.</p>
                    </div>
                </div>
            </div>
        {% endif %}

        <div class="columns is-multiline">
            {% if tasks_todo %}
                <div class="column is-12">
                    <h2 class="is-size-4">Todo</h2>
                </div>

                {% for task in tasks_todo %}
                    <div class="column is-4">
                        <div class="notification">
                            <h3 class="is-size-5">{{ task.title }}</h3>
                            <p>Registered time: {{ task.registered_time }} min</p>

                            <hr>

                            <a href="{% url 'project:task' project.id task.id %}" class="button is-success">Details</a>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}

            {% if tasks_done %}
                <div class="column is-12">
                    <h2 class="is-size-4">Done</h2>
                </div>

                {% for task in tasks_done %}
                    <div class="column is-4">
                        <div class="notification">
                            <h3 class="is-size-5">{{ task.title }}</h3>
                            <p>Registered time: {{ task.registered_time }} min</p>

                            <hr>

                            <a href="{% url 'project:task' project.id task.id %}" class="button is-success">Details</a>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
            {% if tasks_archived %}
                <div class="column is-12">
                    <h2 class="is-size-4">Archived</h2>
                </div>

                {% for task in tasks_archived %}
                    <div class="column is-4">
                        <div class="notification">
                            <h3 class="is-size-5">{{ task.title }}</h3>
                            <p>Registered time: {{ task.registered_time }} min</p>

                            <hr>

                            <a href="{% url 'project:task' project.id task.id %}" class="button is-success">Details</a>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>

        <div class="modal" :class="{'is-active': showAddTaskModal }">
            <div class="modal-background"></div>

            <form method="post" action="." @submit="validateForm">
                {% csrf_token %}

                <div class="modal-card">
                    <div class="modal-card-head">
                        <p class="modal-card-title">Add task</p>
                    </div>

                    <div class="modal-card-body">
                        <div class="field">
                            <label>Title</label>
                            <div class="control">
                                <input type="text" name="title" id="id_title" v-model="title" class="input">
                            </div>
                        </div>

                        <div class="notification is-danger" v-if="showError">
                            The title field is missing!
                        </div>
                    </div>

                    <footer class="modal-card-foot">
                        <button class="button is-success">Submit</button>
                        <button class="button" @click="showAddTaskModal = !showAddTaskModal">Cancel</button>
                    </footer>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        const ProjectApp = {
            data() {
                return {
                    showAddTaskModal: false,
                    title: '',
                    showError: false
                }
            },
            delimiters: ['[[', ']]'],
            methods: {
                validateForm(e) {
                    if (this.title) {
                        return true
                    }

                    this.showError = true

                    e.preventDefault()

                    return false
                }
            }
        }

        Vue.createApp(ProjectApp).mount('#project-app')
    </script>
{% endblock %}

apps/project/templates/project/task.html
{% extends 'main/base.html' %}
{% load dashboardextras %}

{% block title %}{{ task.title }} | {% endblock %}

{% block content %}
    <div id="project-app">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a href="#">Dashboard</a></li>
                <li><a href="{% url 'project:projects' %}">Projects</a></li>
                <li><a href="{% url 'project:project' project.id %}">{{ project.title }}</a></li>
                <li class="is-active"><a href="{% url 'project:task' project.id task.id %}" aria-current="page">{{ task.title }}</a></li>
            </ul>
        </nav>

        <div class="columns">
            <div class="column">
                <h1 class="title">{{ task.title }} ({{ task.get_status_display }})</h1>
                <div class="buttons">
                    {% if request.user.is_staff %}
                        <a href="{% url 'project:edit_task' project.id task.id %}" class="button is-warning">Edit task</a>
                    {% endif %}
                    <a href="{% url 'project:project' project.id %}" class="button">Back</a>


                </div>
                <h2 class="subtitle mt-6">Register time</h2>
                    <form method="post" action=".">
                        {% csrf_token %}
                        <div class="field is-grouped">
                            <div class="control">
                                <div class="select">
                                    <select name="hours">
                                        <option value="0">0h</option>
                                        {% for i in "x"|rjust:"10" %}
                                            <option value="{{ forloop.counter }}">{{ forloop.counter }}h</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>

                            <div class="control">
                                <div class="select">
                                    <select name="minutes">
                                        <option value="0">0m</option>
                                        {% for i in "x"|rjust:"59" %}
                                            <option value="{{ forloop.counter }}">{{ forloop.counter }}m</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>

                        </div>

                        <div class="field">
                            <label>Date</label>
                            <div class="control col-xl-2">
                                <input type="date" id="id_date" name="date" class="input" value="{{ today|date:'Y-m-d' }}" placeholder="yyyy-mm-dd">
                            </div>
                        </div>
                        <div class="field">
                            <div class="control">
                                <button class="button is-success">Submit</button>
                            </div>
                        </div>
                    </form>
            </div>
        </div>

        <div class="columns">
            <div class="column is-12">
                <hr>
                <h2 class="subtitle">Logged entries</h2>

                {% if task.entries.all %}
                    <table class="table is-fullwidth" style="text-align: left;">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>User</th>
                                <th>Time</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for entry in task.entries.all %}
                                <tr>
                                    <td>{{ entry.created_at }}</td>
                                    <td>{% firstof entry.created_by.get_full_name entry.created_by.username %}</td>
                                    <td>{{ entry.minutes|format_minutes }}</td>
                                    <td>
                                        {% if request.user.is_staff %}
                                            <a href="{% url 'project:edit_entry' project.id team.id entry.id %}">Edit</a>
                                            <a href="{% url 'project:delete_entry' project.id team.id entry.id %}">Delete</a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>

                        <tfoot>
                            <tr>
                                <th colspan="2">Total</th>
                                <th colspan="2">{{ task.registered_time|format_minutes }}</th>
                            </tr>
                        </tfoot>
                    </table>
                {% else %}
                    <p>No entries</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}