apps/team/urls.py
from django.urls import path
from .views import team, add_team, edit_team, activate_team, invite

app_name = "team"

urlpatterns = [
    path("add_team/", add_team, name="add_team"),
    path("edit_team/", edit_team, name="edit_team"),
    path("invite/", invite, name="invite"),
    path("activate_team/<int:team_id>", activate_team, name="activate_team"),
    path("<int:team_id>/", team, name="team"),
]

workingtime/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.main.views import home, privacy, terms, plans, signup, login_view
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", home, name="home"),
    path("privacy", privacy, name="privacy"),
    path("terms", terms, name="terms"),
    path("plans", plans, name="plans"),
    path('admin/', admin.site.urls),

    path("signup/", signup, name="signup"),
    path("login/", login_view, name="login"),
    # path("login/", auth_views.LoginView.as_view(template_name="main/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("dashboard/", include("apps.dashboard.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/team/models.py
from django.db import models
from django.contrib.auth.models import User


class Team(models.Model):
    ACTIVE = "active"
    DELETED = "deleted"

    CHOICES_STATUS = (
        (ACTIVE, "Active"),
        (DELETED, "Deleted"),
    )

    title = models.CharField(max_length=255)
    members = models.ManyToManyField(User, related_name="teams")
    created_by = models.ForeignKey(User, related_name="created_teams", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=ACTIVE)

    class Meta:
        ordering = ["title"]

    def __str__(self):
        return self.title


class Invitation(models.Model):

    # Status
    INVITED = "invited"
    ACCEPTED = "accepted"

    CHOICES_STATUS = (
        (INVITED, "Invited"),
        (ACCEPTED, "Accepted"),
    )

    team = models.ForeignKey(Team, related_name="invitations", on_delete=models.CASCADE)
    email = models.EmailField()
    code = models.CharField(max_length=20)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=INVITED)
    date_sent = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

apps/team/views.py
import random
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from .models import Team, Invitation
from django.contrib.auth.decorators import login_required
from .utilities import send_invitation, send_invitation_accepted
from apps.main.decorators import admin_only


@login_required(login_url='login')
def team(request, team_id):
    team = get_object_or_404(Team, pk=team_id, status=Team.ACTIVE, members__in=[request.user])
    invitations = team.invitations.filter(status=Invitation.INVITED)

    return render(request, "team/team.html", {'team': team, 'invitations': invitations})


@login_required(login_url='login')
def activate_team(request, team_id):
    team = get_object_or_404(Team, pk=team_id, status=Team.ACTIVE, members__in=[request.user])
    userprofile = request.user.userprofile
    userprofile.active_team_id = team_id
    userprofile.save()

    messages.info(request, "The team has been activated")

    return redirect("team:team", team_id=team_id)


@login_required(login_url='login')
@admin_only
def edit_team(request):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE,
                             members__in=[request.user])
    if request.method == 'POST':
        title = request.POST.get("title")

        if title:
            team.title = title
            team.save()

            messages.info(request, "The changes have been saved successfully")

            return redirect("team:team", team_id=team.id)

    return render(request, "team/edit_team.html", {"team": team})


@login_required(login_url='login')
@admin_only
def add_team(request):
    if request.method == 'POST':
        title = request.POST.get("title")

        if title:
            team = Team.objects.create(title=title, created_by=request.user)
            team.members.add(request.user)
            team.save()

            userprofile = request.user.userprofile
            userprofile.active_team_id = team.id
            userprofile.save()

            return redirect("myaccount")

    return render(request, "team/add_team.html")


@login_required(login_url='login')
@admin_only
def invite(request):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE,
                             members__in=[request.user])

    if request.method == "POST":
        email = request.POST.get('email')

        if email:
            invitations = Invitation.objects.filter(team=team, email=email)

            if not invitations:
                code = "".join(
                    random.choice("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ123456789") for i in range(4))
                invitation = Invitation.objects.create(team=team, email=email, code=code)

                messages.info(request, "The user has been invited")

                send_invitation(email, code, team)

                return redirect('team:team', team_id=team.id)
            else:
                messages.info(request, "The user has already been invited")

    return render(request, 'team/invite.html', {'team': team})

apps/team/templates/team/add_team.html
{% extends 'main/base.html' %}

{% block title %}Add Team | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'myaccount' %}">My account</a></li>
            <li class="is-active"><a href="{% url 'team:add_team' %}" aria-current="page">Add team</a></li>
        </ul>
    </nav>

    <div class="columns" id="team-app">
        <div class="column is-4 is-offset-5">
            <h1 class="title">Add team</h1>

            <form method="post" action="." @submit="validateForm">
                {% csrf_token %}

                <div class="field">
                    <label>Title</label>

                    <div class="control">
                        <input type="text" name="title" id="id_title" v-model="title">
                    </div>
                </div>

                <div class="notification is-danger" v-if="errors.length">
                    <p v-for="error in errors">[[ error ]]</p>
                </div>

                <div class="field">
                    <div class="control">
                        <div class="buttons">
                            <button class="button is-success">Submit</button>
                            <form>
                                <input class="button" value="Back" onclick="history.back()">
                            </form>
{#                            <button class="button" href="{% url 'myaccount' %}">Cancel</button>#}
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        const TeamApp = {
            data() {
                return {
                    title: "",
                    errors: [],
                }
            },
            delimiters: ['[[', ']]'],
            methods: {
                validateForm(e) {
                    this.errors = []

                    if (this.title) {
                        return true
                    }

                    e.preventDefault()

                    this.errors.push("The title field cannot be empty!");

                    return false
                }
            }
        }

        Vue.createApp(TeamApp).mount("#team-app")
    </script>
{% endblock %}

apps/team/templates/team/edit_team.html
{% extends 'main/base.html' %}

{% block title %}Edit Team | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'myaccount' %}">My account</a></li>
            <li class="is-active"><a href="{% url 'team:edit_team' %}" aria-current="page">Edit team</a></li>
        </ul>
    </nav>

    <div class="columns" id="team-app">
        <div class="column is-4 is-offset-5">
            <h1 class="title">Edit team</h1>

            <form method="post" action="." @submit="validateForm">
                {% csrf_token %}

                <div class="field">
                    <label>Title</label>

                    <div class="control">
                        <input type="text" name="title" id="id_title" v-model="title">
                    </div>
                </div>

                <div class="notification is-danger" v-if="errors.length">
                    <p v-for="error in errors">[[ error ]]</p>
                </div>

                <div class="field">
                    <div class="control">
                        <button class="button is-success">Save changes</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        const TeamApp = {
            data() {
                return {
                    title: "{{ team.title }}",
                    errors: [],
                }
            },
            delimiters: ['[[', ']]'],
            methods: {
                validateForm(e) {
                    this.errors = []

                    if (this.title) {
                        return true
                    }

                    e.preventDefault()

                    this.errors.push("The title field is empty!");

                    return false
                }
            }
        }

        Vue.createApp(TeamApp).mount("#team-app")
    </script>
{% endblock %}

apps/team/templates/team/email_accepted_invitation.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Working time</title>
        <style type="text/css">
            html {
                width: 100%;
            }
            body {
                width: 100%;
                font-family: Arial;
                font-size: 14px;
                background-color: #fff;
                color: #333;
            }
            a {
                color: #111;
            }
        </style>
    </head>

    <body>
        <table width="100%" cellspacing="0" cellpadding="0">
            <tr>
                <td>
                    <h1>Working time</h1>
                </td>
            </tr>
            <tr>
                <td>
                    <p>{{ invitation.email }} accepted your invitation</p>
                </td>
            </tr>
        </table>
    </body>
</html>

apps/team/templates/team/email_invitation.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Working time</title>
        <style type="text/css">
            html {
                width: 100%;
            }
            body {
                width: 100%;
                font-family: Arial;
                font-size: 14px;
                background-color: #fff;
                color: #333;
            }
            a {
                color: #111;
            }
        </style>
    </head>

    <body>
        <table width="100%" cellspacing="0" cellpadding="0">
            <tr>
                <td>
                    <h1>Working time - invitation to {{ team.title }}</h1>
                </td>
            </tr>
            <tr>
                <td>
                    <p>You are invited to join {{ team.title }}</p>
                    <p>Click the link bellow to log in ot sign up. Your activation code is - {{ code }}</p>
                </td>
            </tr>
            <tr>
                <td>
                    <a href="{{ acceptation_url }}">Accept invitation</a>
                </td>
            </tr>
        </table>
    </body>
</html>

apps/team/templates/team/invite.html
{% extends 'main/base.html' %}

{% block title %}Invite member | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'myaccount' %}">My account</a></li>
            <li><a href="{% url 'team:team' team.id %}">{{ team.title }}</a></li>
            <li class="is-active"><a href="{% url 'team:invite' %}" aria-current="page">Invite member</a></li>
        </ul>
    </nav>

    <div class="columns is-multiline" id="invite-app">
        <div class="column is-4">
            <h1 class="title">Invite member</h1>

            <div class="notification is-danger" v-if="errors.length">
                <p v-for="error in errors">[[ error ]]</p>
            </div>

            <form method="post" action="." @submit="validateForm" novalidate>
                {% csrf_token %}

                <div class="field">
                    <label>E-mail</label>

                    <div class="control">
                        <input type="email" name="email" id="id_email" v-model="email" class="input">
                    </div>
                </div>

                <div class="field">
                    <div class="control">
                        <button class="button is-success">Send invitation</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script>
    const InviteApp = {
        data() {
            return {
                email: '',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                if (this.validateEmail(this.email)) {
                    return true
                }

                this.errors = ['Invalid e-mail']

                e.preventDefault()

                return false
            },
            validateEmail(email) {
                if (/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/.test(email)) {
                    return true
                }

                return false
            }
        }
    }

    Vue.createApp(InviteApp).mount('#invite-app')
</script>
{% endblock %}

apps/team/templates/team/team.html
{% extends 'main/base.html' %}

{% block title %}{{ team.title }} | {% endblock %}

{% block content %}
    <br>
    <nav class="breadcrumb" aria-label="breadcrumb">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'myaccount' %}">My account</a></li>
            <li class="is-active"><a href="{% url 'team:team' team.id %}" aria-current="page">{{ team.title }}</a></li>
        </ul>
    </nav>

    <div class="columns is-multiline" id="team-app">
        <div class="column is-4">
            <h1 class="title">{{ team.title }}</h1>

            {% if request.user == team.created_by %}
                <a href="{% url 'team:invite' %}" class="button is-primary">Invite users</a>
            {% endif %}
            <a class="button" href="{% url 'myaccount' %}">Back</a>
            <hr>

            <h2 class="subtitle mt-6">Members</h2>

            {% for member in team.members.all %}
                <p>{{ member.first_name }} {{ member.last_name }}<br>
                    {{ member.username }}
                    <hr>
                </p>
            {% endfor %}

            <hr>

            <h2 class="subtitle mt-6">Invited members</h2>
            {% for member in invitations %}
                <p>{{ member.email }} - {{ member.date_sent|timesince }} ago</p>
            {% endfor %}
        </div>

        {% if team.created_by == request.user %}
            <div class="column is-12">
                <hr>
                <h3 class="subtitle">Owner actions</h3>

                <a href="{% url "team:edit_team" %}" class="button is-warning">Edit Team</a>
            </div>
        {% endif %}

    </div>

{% endblock %}